#!/usr/bin/env bash

function error {
	NAME=$1

	printf "$1"
	exit 1
}

PROG="showman"

# this builds the cli
scripts/bundle

if [ $? -ne 0 ]; then
	error "Unable to create release. Please check and try again"
fi

echo "Successfully generated $PROG"
