on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: ./metadata/changes/latest.txt
          draft: false
          prerelease: false

      - name: Set Environment
        run: echo ::set-env name=APP_VERSION::$(cat VERSION)
        run: echo ::set-env name=GIT_COUNT::$(git rev-list HEAD --count)
        run: echo ::set-env name=GIT_HASH::$(git rev-parse --short HEAD)

      - name: Build Go app
        uses: jbrodriguez/go-release-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          build_flags: -ldflags "-s -w -X main.Version=${{ env.APP_VERSION }}-${{ env.GIT_COUNT }}.${{ env.GIT_HASH }}" -gcflags "all=-trimpath=$GOPATH" -v
          project_path: "./cli"
          binary_name: "showman"
          upload_url: ${{ steps.create_release.outputs.upload_url }}